// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tzbhcdsmbaunbeuceajk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR6YmhjZHNtYmF1bmJldWNlYWprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4MTYxODQsImV4cCI6MjA2NTM5MjE4NH0.1zpAVcAF9vrNpUP0o82HAJNk57Lt15lmI5STzsW0zZ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});